global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: tollbooth-gateway
    static_configs:
      - targets: ['gateway:3000']
    metrics_path: /metrics

  - job_name: tollbooth-control-plane
    static_configs:
      - targets: ['control-plane:3001']
    metrics_path: /metrics
