/** Audit action names. Stored as plain strings, so adding one needs no migration. */
export const AuditAction = {
  // Authentication
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',

  // API Key & Gateway
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_DELETED: 'API_KEY_DELETED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_REQUEST_RECORDED: 'API_REQUEST_RECORDED',

  // Admin Actions
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  BUDGET_CHANGED: 'BUDGET_CHANGED',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
  TENANT_CREATED: 'TENANT_CREATED',
  TENANT_UPDATED: 'TENANT_UPDATED',
  TENANT_DELETED: 'TENANT_DELETED',

  // AI Governance
  PROVIDER_CHANGED: 'PROVIDER_CHANGED',
  MODEL_ACCESS_CHANGED: 'MODEL_ACCESS_CHANGED',

  // Teams & Projects
  TEAM_CREATED: 'TEAM_CREATED',
  TEAM_UPDATED: 'TEAM_UPDATED',
  TEAM_DELETED: 'TEAM_DELETED',
  TEAM_MEMBER_ADDED: 'TEAM_MEMBER_ADDED',
  TEAM_MEMBER_REMOVED: 'TEAM_MEMBER_REMOVED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_DELETED: 'PROJECT_DELETED',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

